name: cars_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.13.0

dependencies:
  analyzer: 5.13.0
  bloc: 8.1.2
  chopper: 6.1.3
  dartz: 0.10.1
  easy_localization: 3.0.3
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_colorpicker: 1.0.3
  flutter_map: 4.0.0
  freezed_annotation: 2.4.1
  geocoder_buddy: 1.0.1
  get_it: 7.6.0
  http: 0.13.6
  injecteo: 1.0.0
  json_annotation: 4.8.1
  latlong2: 0.8.0
  linteo:
    path: /Users/kfalinski/development/opensource_repos/linteo
  mocktail: 1.0.0
  provider: 6.0.5

dev_dependencies:
  bloc_test: 9.1.4
  build_runner: 2.3.3
  chopper_generator: 6.0.0
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.1
  injecteo_generator: 1.0.1
  json_serializable: 6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/translations/