name: cars_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  chopper: 6.1.3
  get_it: 7.6.0
  analyzer: 5.13.0
  equatable: 2.0.5
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  provider: 6.0.5
  dartz: 0.10.1
  injecteo: 1.0.0
  mocktail: 1.0.0
  easy_localization: 3.0.3
  flutter_map: 4.0.0
  latlong2: 0.8.0
  geocoder_buddy: 1.0.1
#  location: 5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  chopper_generator: 6.0.0
  build_runner: 2.3.3
  bloc_test: 9.1.4
  freezed: 2.4.1
  injecteo_generator: 1.0.1
  json_serializable: 6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/translations/